// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZzw5hQffZtG11aeGO9FxJHiNJiZmEjSk',
    appId: '1:710384504028:web:47733197ff59ede3abf819',
    messagingSenderId: '710384504028',
    projectId: 'dlrg-weeze-manager',
    authDomain: 'dlrg-weeze-manager.firebaseapp.com',
    databaseURL: 'https://dlrg-weeze-manager-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'dlrg-weeze-manager.appspot.com',
    measurementId: 'G-Q0XNW8RRPQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtQWJrXOEO3210We4nWCEbQ-X3NykeJP8',
    appId: '1:710384504028:android:64d3bcdec7870787abf819',
    messagingSenderId: '710384504028',
    projectId: 'dlrg-weeze-manager',
    databaseURL: 'https://dlrg-weeze-manager-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'dlrg-weeze-manager.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZzw5hQffZtG11aeGO9FxJHiNJiZmEjSk',
    appId: '1:710384504028:web:872b0d1c9d83739fabf819',
    messagingSenderId: '710384504028',
    projectId: 'dlrg-weeze-manager',
    authDomain: 'dlrg-weeze-manager.firebaseapp.com',
    databaseURL: 'https://dlrg-weeze-manager-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'dlrg-weeze-manager.appspot.com',
    measurementId: 'G-BZZZ3JYLTJ',
  );
}
